version: "3"

services:
  ai-bot:
    container_name: ai-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 8000:8000
    networks:
      - reports-net
    
networks:
  reports-net:
    name: reports-net
    external: true