version: "3"

services:
  ai-bot:
    container_name: ai-bot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CA: ${CA}
        PASS: ${PASS}
        HOSTS: ${HOSTS}
        SOURCE_DIR: ${SOURCE_DIR}
        CHUNK_SIZE: ${CHUNK_SIZE}
        CHUNK_OVERLAP: ${CHUNK_OVERLAP}
        SERVICE_ACCOUNT_ID: ${SERVICE_ACCOUNT_ID}
        KEY_ID: ${KEY_ID}
        KEY: ${KEY}
    restart: always
    ports:
      - 8000:8000
    networks:
      - reports-net
    
networks:
  reports-net:
    name: reports-net
    external: true